version: '3.8'
services:
  location-db: 
    image: postgres:13
    restart: always
    hostname: ${DB_HOST}
    ports:
      - ${DB_PORT}:5434
    environment: 
       POSTGRES_USER: ${DB_USERNAME}
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB: ${DB_NAME}
    networks:
      - location
networks:
  location:
