version: '3.8'
services:
  location-db: 
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
       - "5432:5434"
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 123
       POSTGRES_DB: location
    networks:
      - location
networks:
  location:
